config/routes.rb
Rails.application.routes.draw do
#   get 'admin/index'
#
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'sessions/check'
#
  # get 'home/index'
#
  resources :users
  resources :thongtincongviecs, only: [:index, :show]
#   # resources :diadiems
#   resources :vitricongviecs
  resources :thongtincanhans, only: [:new, :create, :success]
  get 'thongtincanhans/success'
#   # resources :congties
#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root :to => 'home#index'

controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
end
    get 'admin/home/index'
    get 'admin' => 'admin/home#index'
  namespace :admin do
        # Directs /admin/products/* to Admin::ProductsController
        # (app/controllers/admin/products_controller.rb)
        #   resources :users

        #   resources :vitricongviecs
        #   resources :thongtincanhans
          resources :vitricongviecs
          resources :congties
          resources :diadiems
          resources :thongtincongviecs
          resources :thongtincanhans
    end
end

app/models/thongtincongviec.rb
class Thongtincongviec < ApplicationRecord
	 belongs_to :congty
	 belongs_to :vitricongviec
	 belongs_to :diadiem
	 # has_many :thongtincongviecs, dependent: :destroy

	 def self.search(congty_id, diadiem_id, vitricongviec_id)
		 if congty_id and diadiem_id and vitricongviec_id
			 where('congty_id like ? and diadiem_id like ? and vitricongviec_id like ?',
						 "%#{congty_id}%", "%#{diadiem_id}%", "%#{vitricongviec_id}%")
		 else
			 all
		 end
	 end
end

app/controllers/admin/thongtincongviecs_controller.rb
class Admin::ThongtincongviecsController < ApplicationController
  before_action :authorize
  layout "admin"
  before_action :set_thongtincongviec, only: [:show, :edit, :update, :destroy]

  # GET /thongtincongviecs
  # GET /thongtincongviecs.json
  def index
    @thongtincongviecs = Thongtincongviec.all
  end

  # GET /thongtincongviecs/1
  # GET /thongtincongviecs/1.json
  def show
  end

  # GET /thongtincongviecs/new
  def new
    @thongtincongviec = Thongtincongviec.new
  end

  # GET /thongtincongviecs/1/edit
  def edit
  end

  # POST /thongtincongviecs
  # POST /thongtincongviecs.json
  def create
    @thongtincongviec = Thongtincongviec.new(thongtincongviec_params)

    respond_to do |format|
      if @thongtincongviec.save
        format.html { redirect_to admin_thongtincongviecs_url, notice: 'Thongtincongviec was successfully created.' }
        format.json { render :show, status: :created, location: @thongtincongviec }
      else
        format.html { render :new }
        format.json { render json: @thongtincongviec.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thongtincongviecs/1
  # PATCH/PUT /thongtincongviecs/1.json
  def update
    respond_to do |format|
      if @thongtincongviec.update(thongtincongviec_params)
        format.html { redirect_to edit_admin_thongtincongviec_path(@thongtincongviec), notice: 'Thongtincongviec was successfully updated.' }
        format.json { render :show, status: :ok, location: @thongtincongviec }
      else
        format.html { render :edit }
        format.json { render json: @thongtincongviec.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thongtincongviecs/1
  # DELETE /thongtincongviecs/1.json
  def destroy
    @thongtincongviec.destroy
    respond_to do |format|
      format.html { redirect_to admin_thongtincongviecs_url, notice: 'Thongtincongviec was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_thongtincongviec
    @thongtincongviec = Thongtincongviec.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def thongtincongviec_params
    params.require(:thongtincongviec).permit(:tencongviec, :congty_id, :vitricongviec_id, :diadiem_id, :sohoso, :mavitri, :thoihannophoso, :thongtinvitri, :mota, :yeucau, :chedoluong)
  end
end

app/controllers/thongtincongviecs_controller.rb
class ThongtincongviecsController < ApplicationController
  before_action :set_thongtincongviec, only: [:show, :edit, :update, :destroy]

  # GET /thongtincongviecs
  # GET /thongtincongviecs.json
  def index
    if params[:congty_id] and params[:diadiem_id] and params[:vitricongviec_id]
      @thongtincongviecs = Thongtincongviec.search(params[:congty_id], params[:diadiem_id], params[:vitricongviec_id])
    else
      @thongtincongviecs = Thongtincongviec.all
    end
  end

  # GET /thongtincongviecs/1
  # GET /thongtincongviecs/1.json
  def show
  end

  # GET /thongtincongviecs/new
  def new
    @thongtincongviec = Thongtincongviec.new
  end

  # GET /thongtincongviecs/1/edit
  def edit
  end

  # POST /thongtincongviecs
  # POST /thongtincongviecs.json
  def create
    @thongtincongviec = Thongtincongviec.new(thongtincongviec_params)

    respond_to do |format|
      if @thongtincongviec.save
        format.html { redirect_to @thongtincongviec, notice: 'Thongtincongviec was successfully created.' }
        format.json { render :show, status: :created, location: @thongtincongviec }
      else
        format.html { render :new }
        format.json { render json: @thongtincongviec.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thongtincongviecs/1
  # PATCH/PUT /thongtincongviecs/1.json
  def update
    respond_to do |format|
      if @thongtincongviec.update(thongtincongviec_params)
        format.html { redirect_to @thongtincongviec, notice: 'Thongtincongviec was successfully updated.' }
        format.json { render :show, status: :ok, location: @thongtincongviec }
      else
        format.html { render :edit }
        format.json { render json: @thongtincongviec.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thongtincongviecs/1
  # DELETE /thongtincongviecs/1.json
  def destroy
    @thongtincongviec.destroy
    respond_to do |format|
      format.html { redirect_to thongtincongviecs_url, notice: 'Thongtincongviec was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thongtincongviec
      @thongtincongviec = Thongtincongviec.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thongtincongviec_params
      params.require(:thongtincongviec).permit(:tencongviec, :congty_id, :vitricongviec_id, :diadiem_id, :sohoso, :mavitri, :thoihannophoso, :thongtinvitri, :mota, :yeucau, :chedoluong)
    end
end

app/helpers/admin/thongtincongviecs_helper.rb
module Admin::ThongtincongviecsHelper
end

app/helpers/thongtincongviecs_helper.rb
module ThongtincongviecsHelper
end

app/views/admin/thongtincongviecs/_form.html.erb
<%= form_with(model: [:admin, thongtincongviec], local: true, class: "form-horizontal") do |form| %>
  <% if thongtincongviec.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thongtincongviec.errors.count, "error") %> prohibited this thongtincongviec from being saved:</h2>

      <ul>
      <% thongtincongviec.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="content-group">
    <div class="form-group">
      <%= form.label :tencongviec , "Tên công việc",class: "control-label col-lg-2"%>
      <div class="col-lg-10">
        <%= form.text_field :tencongviec, id: :thongtincongviec_tencongviec, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :congty_id , "Công ty",class: "control-label col-lg-2"%>
      <div class="col-lg-10">
        <%= form.collection_select :congty_id, Congty.all, :id, :tencongty, {prompt: true}, {class: "form-control"} %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :vitricongviec_id , "Vị trí",class: "control-label col-lg-2"%>
      <div class="col-lg-10">
        <%= form.collection_select :vitricongviec_id, Vitricongviec.all, :id, :tenvitri, {prompt: true}, {class: "form-control"} %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :diadiem_id , "Địa điểm",class: "control-label col-lg-2"%>
      <div class="col-lg-10">
        <%= form.collection_select :diadiem_id, Diadiem.all, :id, :tendiadiem, {prompt: true}, {class: "form-control"} %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :sohoso , "Số hồ sơ",class: "control-label col-lg-2"%>
      <div class="col-lg-10">
        <%= form.text_field :sohoso, id: :thongtincongviec_sohoso, class: "form-control"%>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :mavitri , "Mã vị trí",class: "control-label col-lg-2"%>
      <div class="col-lg-10">
        <%= form.text_field :mavitri, id: :thongtincongviec_mavitri, class: "form-control"%>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :thoihannophoso , "Thờí hạn nộp hồ sơ",class: "control-label col-lg-2"%>
      <div class="col-lg-10">
        <%= form.date_select :thoihannophoso, id: :thongtincongviec_thoihannophoso, class: 'datepicker' %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :thongtinvitri , "Thông tin vị trí",class: "control-label col-lg-2"%>
      <div class="col-lg-10">
        <%= form.text_field :thongtinvitri, id: :thongtincongviec_thongtinvitri, class: "form-control"%>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :mota , "Mô tả",class: "control-label col-lg-2"%>
      <div class="col-lg-10">
        <%= form.text_area :mota, id: :thongtincongviec_mota, cols: 5, rows: 5, class: "form-control"%>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :yeucau , "Yêu cầu",class: "control-label col-lg-2"%>
      <div class="col-lg-10">
        <%= form.text_area :yeucau, id: :thongtincongviec_yeucau, cols: 5, rows: 5, class: "form-control"%>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :chedoluong , "Chế độ lương",class: "control-label col-lg-2"%>
      <div class="col-lg-10">
        <%= form.text_area :chedoluong, id: :thongtincongviec_chedoluong, cols: 5, rows: 5, class: "form-control"%>
      </div>
    </div>

  </fieldset>
  <div class="actions text-right">
    <%= form.submit 'Submit', class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/admin/thongtincongviecs/edit.html.erb
<% if notice.present? %>
  <div class="alert alert-success alert-styled-left alert-arrow-left alert-bordered">
    <button type="button" class="close" data-dismiss="alert"><span>&times;</span><span class="sr-only">Close</span></button>
    <span class="text-semibold"><%= notice %></span>
  </div>
<% end %>
<div class="panel panel-flat">
  <div class="panel-heading">
    <h1 class="panel-title">Editing thông tin công việc</h1>
  </div>
  <div class="panel-body">
    <%= render 'form', thongtincongviec: @thongtincongviec %>
    <%= link_to 'Back', admin_thongtincongviecs_path %>
  </div>

</div>

app/views/admin/thongtincongviecs/index.html.erb
<% if notice.present? %>
  <div class="alert alert-success alert-styled-left alert-arrow-left alert-bordered">
    <button type="button" class="close" data-dismiss="alert"><span>&times;</span><span class="sr-only">Close</span></button>
    <span class="text-semibold"><%= notice %></span>
  </div>
<% end %>

<div class="panel panel-flat">
  <div class="panel-heading">


    <div class="col-md-9">
      <h2 class="panel-title">Thông tin công việc</h2>
    </div>
    <div class="col-md-3">
      <%= link_to 'Tạo mới', new_admin_thongtincongviec_path , class: 'btn btn-primary btn-lg', id: 'new'%>
    </div>
  </div>
  <table class="table datatable-basic table-bordered">
    <thead>
    <tr>
      <th>Tên công việc</th>
      <th>Công ty</th>
      <th>Vị trí công việc</th>
      <th>Địa điểm</th>
      <th>Số hồ sơ</th>
      <th>Mã vị trí</th>
      <th>Thời hạn nộp hồ sơ</th>
      <th>Thông tin vị trí</th>
      <th>Mô tả</th>
      <th>Yêu cầu</th>
      <th>Chế độ lương</th>
      <th class="text-center">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @thongtincongviecs.each do |thongtincongviec| %>
      <tr>
        <td><%= thongtincongviec.tencongviec %></td>
        <td><%= thongtincongviec.congty.tencongty %></td>
        <td><%= thongtincongviec.vitricongviec.tenvitri %></td>
        <td><%= thongtincongviec.diadiem.tendiadiem %></td>
        <td><%= thongtincongviec.sohoso %></td>
        <td><%= thongtincongviec.mavitri %></td>
        <td><%= thongtincongviec.thoihannophoso %></td>
        <td><%= thongtincongviec.thongtinvitri %></td>
        <td><%= thongtincongviec.mota %></td>
        <td><%= thongtincongviec.yeucau %></td>
        <td><%= thongtincongviec.chedoluong %></td>
        <td class="text-center">
          <ul class="icons-list">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="icon-menu9"></i>
              </a>

              <ul class="dropdown-menu dropdown-menu-right">
                <!--              <li><%#= link_to 'Show', [:admin, vitricongviec] %></li>-->
                <li><%= link_to 'Edit', edit_admin_thongtincongviec_path(thongtincongviec) %></li>
                <li><%= link_to 'Destroy', [:admin, thongtincongviec], method: :delete, data: { confirm: 'Are you sure?' } %></li>
              </ul>
            </li>
          </ul>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/thongtincongviecs/new.html.erb
<div class="panel panel-flat">
  <div class="panel-heading">
    <h1 class="panel-title">Tạo mới thông tin công việc</h1>
  </div>
  <div class="panel-body">
    <%= render 'form', thongtincongviec: @thongtincongviec %>
    <%= link_to 'Back', admin_thongtincongviecs_path %>
  </div>

</div>

app/views/admin/thongtincongviecs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tencongviec:</strong>
  <%= @thongtincongviec.tencongviec %>
</p>

<p>
  <strong>Congty:</strong>
  <%= @thongtincongviec.congty.tencongty %>
</p>

<p>
  <strong>Vitricongviec:</strong>
  <%= @thongtincongviec.vitricongviec.tenvitri %>
</p>

<p>
  <strong>Diadiem:</strong>
  <%= @thongtincongviec.diadiem.tendiadiem %>
</p>

<p>
  <strong>Sohoso:</strong>
  <%= @thongtincongviec.sohoso %>
</p>

<p>
  <strong>Mavitri:</strong>
  <%= @thongtincongviec.mavitri %>
</p>

<p>
  <strong>Thoihannophoso:</strong>
  <%= @thongtincongviec.thoihannophoso %>
</p>

<p>
  <strong>Thongtinvitri:</strong>
  <%= @thongtincongviec.thongtinvitri %>
</p>

<p>
  <strong>Mota:</strong>
  <%= @thongtincongviec.mota %>
</p>

<p>
  <strong>Yeucau:</strong>
  <%= @thongtincongviec.yeucau %>
</p>

<p>
  <strong>Chedoluong:</strong>
  <%= @thongtincongviec.chedoluong %>
</p>

<%= link_to 'Edit', edit_thongtincongviec_path(@thongtincongviec) %> |
<%= link_to 'Back', thongtincongviecs_path %>