config/routes.rb
Rails.application.routes.draw do
#   get 'admin/index'
#
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'sessions/check'
#
  # get 'home/index'
#
  resources :users
  resources :thongtincongviecs, only: [:index, :show]
#   # resources :diadiems
#   resources :vitricongviecs
  resources :thongtincanhans, only: [:new, :create, :success]
  get 'thongtincanhans/success'
#   # resources :congties
#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root :to => 'home#index'

controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
end
    get 'admin/home/index'
    get 'admin' => 'admin/home#index'
  namespace :admin do
        # Directs /admin/products/* to Admin::ProductsController
        # (app/controllers/admin/products_controller.rb)
        #   resources :users

        #   resources :vitricongviecs
        #   resources :thongtincanhans
          resources :vitricongviecs
          resources :congties
          resources :diadiems
          resources :thongtincongviecs
          resources :thongtincanhans
    end
end

app/models/vitricongviec.rb
class Vitricongviec < ApplicationRecord
  has_many :thongtincongviecs, dependent: :destroy
# has_many :thongtincanhans, dependent: :destroy
end

app/controllers/admin/vitricongviecs_controller.rb
class Admin::VitricongviecsController < ApplicationController
  before_action :authorize
  layout 'admin'
  before_action :set_vitricongviec, only: [:show, :edit, :update, :destroy]

  # GET /vitricongviecs
  # GET /vitricongviecs.json
  def index
    @vitricongviecs = Vitricongviec.all
  end

  # GET /vitricongviecs/1
  # GET /vitricongviecs/1.json
  def show
  end

  # GET /vitricongviecs/new
  def new
    @vitricongviec = Vitricongviec.new
  end

  # GET /vitricongviecs/1/edit
  def edit
  end

  # POST /vitricongviecs
  # POST /vitricongviecs.json
  def create
    @vitricongviec = Vitricongviec.new(vitricongviec_params)

    respond_to do |format|
      if @vitricongviec.save
        format.html { redirect_to admin_vitricongviecs_url, notice: 'Vitricongviec was successfully created.' }
        format.json { render :show, status: :created, location: @vitricongviec }
      else
        format.html { render :new }
        format.json { render json: @vitricongviec.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vitricongviecs/1
  # PATCH/PUT /vitricongviecs/1.json
  def update
    respond_to do |format|
      if @vitricongviec.update(vitricongviec_params)
        format.html { redirect_to edit_admin_vitricongviec_path(@vitricongviec), notice: 'Vitricongviec was successfully updated.' }
        format.json { render :show, status: :ok, location: @vitricongviec }
      else
        format.html { render :edit }
        format.json { render json: @vitricongviec.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vitricongviecs/1
  # DELETE /vitricongviecs/1.json
  def destroy
    @vitricongviec.destroy
    respond_to do |format|
      format.html { redirect_to admin_vitricongviecs_url, notice: 'Vitricongviec was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vitricongviec
      @vitricongviec = Vitricongviec.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def vitricongviec_params
    #   params.fetch(:vitricongviec, {})
    # end
  def vitricongviec_params
    params.require(:vitricongviec).permit(:tenvitri)
  end
end

app/helpers/admin/vitricongviecs_helper.rb
module Admin::VitricongviecsHelper
end

app/helpers/vitricongviecs_helper.rb
module VitricongviecsHelper
end

app/views/vitricongviecs/_form.html.erb
<%= form_with(model: vitricongviec, local: true) do |form| %>
  <% if vitricongviec.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vitricongviec.errors.count, "error") %> prohibited this vitricongviec from being saved:</h2>

      <ul>
      <% vitricongviec.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tenvitri %>
    <%= form.text_field :tenvitri, id: :vitricongviec_tenvitri %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vitricongviecs/edit.html.erb
<h1>Editing Vitricongviec</h1>

<%= render 'form', vitricongviec: @vitricongviec %>

<%= link_to 'Show', @vitricongviec %> |
<%= link_to 'Back', vitricongviecs_path %>

app/views/vitricongviecs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vitricongviecs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Tenvitri</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vitricongviecs.each do |vitricongviec| %>
      <tr>
        <td><%= vitricongviec.tenvitri %></td>
        <td><%= link_to 'Show', vitricongviec %></td>
        <td><%= link_to 'Edit', edit_vitricongviec_path(vitricongviec) %></td>
        <td><%= link_to 'Destroy', vitricongviec, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vitricongviec', new_vitricongviec_path %>

app/views/vitricongviecs/new.html.erb
<h1>New Vitricongviec</h1>

<%= render 'form', vitricongviec: @vitricongviec %>

<%= link_to 'Back', vitricongviecs_path %>

app/views/vitricongviecs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tenvitri:</strong>
  <%= @vitricongviec.tenvitri %>
</p>

<%= link_to 'Edit', edit_vitricongviec_path(@vitricongviec) %> |
<%= link_to 'Back', vitricongviecs_path %>