config/routes.rb
Rails.application.routes.draw do
#   get 'admin/index'
#
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'sessions/check'
#
  # get 'home/index'
#
  resources :users
  resources :thongtincongviecs, only: [:index, :show]
#   # resources :diadiems
#   resources :vitricongviecs
  resources :thongtincanhans, only: [:new, :create, :success]
  get 'thongtincanhans/success'
#   # resources :congties
#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root :to => 'home#index'

controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
end
    get 'admin/home/index'
    get 'admin' => 'admin/home#index'
  namespace :admin do
        # Directs /admin/products/* to Admin::ProductsController
        # (app/controllers/admin/products_controller.rb)
        #   resources :users

        #   resources :vitricongviecs
        #   resources :thongtincanhans
          resources :vitricongviecs
          resources :congties
          resources :diadiems
          resources :thongtincongviecs
          resources :thongtincanhans
    end
end

app/models/thongtincanhan.rb
class Thongtincanhan < ApplicationRecord
	belongs_to :thongtincongviec
	belongs_to :vitricongviec
	mount_uploader :filedinhkem, AttachmentUploader
end

app/controllers/admin/thongtincanhans_controller.rb
class Admin::ThongtincanhansController < ApplicationController
  before_action :authorize
  layout "admin"
  before_action :set_thongtincanhan, only: [:show, :edit, :update, :destroy]

  # GET /thongtincanhans
  # GET /thongtincanhans.json
  def index
    @thongtincanhans = Thongtincanhan.all
  end

  # GET /thongtincanhans/1
  # GET /thongtincanhans/1.json
  def show
  end

  # GET /thongtincanhans/new
  def new
    @thongtincanhan = Thongtincanhan.new
  end

  # GET /thongtincanhans/1/edit
  def edit
  end

  # POST /thongtincanhans
  # POST /thongtincanhans.json
  def create
    @thongtincanhan = Thongtincanhan.new(thongtincanhan_params)

    respond_to do |format|
      if @thongtincanhan.save
        format.html { redirect_to admin_thongtincanhans_url, notice: 'Thongtincanhan was successfully created.' }
        format.json { render :show, status: :created, location: @thongtincanhan }
      else
        format.html { render :new }
        format.json { render json: @thongtincanhan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thongtincanhans/1
  # PATCH/PUT /thongtincanhans/1.json
  def update
    respond_to do |format|
      if @thongtincanhan.update(thongtincanhan_params)
        format.html { redirect_to edit_admin_thongtincanhan_path, notice: 'Thongtincanhan was successfully updated.' }
        format.json { render :show, status: :ok, location: @thongtincanhan }
      else
        format.html { render :edit }
        format.json { render json: @thongtincanhan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thongtincanhans/1
  # DELETE /thongtincanhans/1.json
  def destroy
    #byebug
    @thongtincanhan.destroy
    respond_to do |format|
      format.html { redirect_to admin_thongtincanhans_url, notice: 'Thongtincanhan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_thongtincanhan
    @thongtincanhan = Thongtincanhan.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def thongtincanhan_params
    params.require(:thongtincanhan).permit(:thongtincongviec_id, :hovaten, :sodienthoai, :email, :vitricongviec_id, :filedinhkem)
  end
end

app/controllers/thongtincanhans_controller.rb
class ThongtincanhansController < ApplicationController
  before_action :set_thongtincanhan, only: [:show, :edit, :update, :destroy]

  # GET /thongtincanhans
  # GET /thongtincanhans.json
  def index
    @thongtincanhans = Thongtincanhan.all
  end

  # GET /thongtincanhans/1
  # GET /thongtincanhans/1.json
  def show
  end

  # GET /thongtincanhans/new
  def new
    @thongtincongviec = Thongtincongviec.find(params[:id])
    @thongtincanhan = Thongtincanhan.new
  end

  # GET /thongtincanhans/1/edit
  def edit
  end

  # POST /thongtincanhans
  # POST /thongtincanhans.json
  def create
    @thongtincanhan = Thongtincanhan.new(thongtincanhan_params)
    if @thongtincanhan.save
      flash[:notice] = 'Hồ sơ đã gửi thành công'
      redirect_to :action => 'success'
    end

    # respond_to do |format|
    #   if @thongtincanhan.save
    #     format.html { redirect_to :action => 'success', notice: 'Thongtincanhan was successfully created.' }
    #     # format.json { render :show, status: :created, location: @thongtincanhan }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @thongtincanhan.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def success
    if !notice
      redirect_to root_path
    end
  end

  # PATCH/PUT /thongtincanhans/1
  # PATCH/PUT /thongtincanhans/1.json
  def update
    respond_to do |format|
      if @thongtincanhan.update(thongtincanhan_params)
        format.html { redirect_to @thongtincanhan, notice: 'Thongtincanhan was successfully updated.' }
        format.json { render :show, status: :ok, location: @thongtincanhan }
      else
        format.html { render :edit }
        format.json { render json: @thongtincanhan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thongtincanhans/1
  # DELETE /thongtincanhans/1.json
  def destroy
    #byebug
    @thongtincanhan.destroy
    respond_to do |format|
      format.html { redirect_to thongtincanhans_url, notice: 'Thongtincanhan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thongtincanhan
      @thongtincanhan = Thongtincanhan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thongtincanhan_params
      params.require(:thongtincanhan).permit(:thongtincongviec_id, :hovaten, :sodienthoai, :email, :vitricongviec_id, :filedinhkem)
    end
end

app/helpers/admin/thongtincanhans_helper.rb
module Admin::ThongtincanhansHelper
end

app/helpers/thongtincanhans_helper.rb
module ThongtincanhansHelper
end

app/views/admin/thongtincanhans/_form.html.erb
<%= form_with(model: [:admin, thongtincanhan], local: true, class: "form-horizontal") do |form| %>
  <% if thongtincanhan.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger alert-styled-left alert-bordered">
        <button type="button" class="close" data-dismiss="alert"><span>&times;</span><span class="sr-only">Close</span></button>
        <span class="text-semibold"><%= pluralize(thongtincanhan.errors.count, "error") %> prohibited this thongtincanhan from being saved:</span>
      </div>


      <% thongtincanhan.errors.full_messages.each do |message| %>
        <div class="alert alert-danger no-border">
          <button type="button" class="close" data-dismiss="alert"><span>&times;</span><span class="sr-only">Close</span></button>
          <%= message %>
        </div>
      <% end %>

    </div>
  <% end %>

  <fieldset class="content-group">
    <div class="form-group">
      <%= form.label :thongtincongviec_id , "Công việc",class: "control-label col-lg-2"%>
      <div class="col-lg-10">
        <%= form.collection_select :thongtincongviec_id, Thongtincongviec.all, :id, :tencongviec, {prompt: true}, {class: "form-control"} %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :hovaten , "Họ và tên",class: "control-label col-lg-2"%>
      <div class="col-lg-10">
        <%= form.text_field :hovaten, id: :thongtincanhan_hovaten, class: "form-control"%>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :sodienthoai , "Số điện thoại",class: "control-label col-lg-2"%>
      <div class="col-lg-10">
        <%= form.text_field :sodienthoai, id: :thongtincanhan_sodienthoai, class: "form-control"%>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :email , "Email",class: "control-label col-lg-2"%>
      <div class="col-lg-10">
        <%= form.text_field :email, id: :thongtincanhan_email, class: "form-control"%>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :vitricongviec_id , "Vị trí công việc",class: "control-label col-lg-2"%>
      <div class="col-lg-10">
        <%= form.collection_select :vitricongviec_id, Vitricongviec.all, :id, :tenvitri, {prompt: true}, {class: "form-control"} %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :filedinhkem , "File đính kèm",class: "control-label col-lg-2"%>
      <div class="col-lg-10">
        <%= form.file_field :filedinhkem, id: :thongtincanhan_filedinhkem, class: "form-control"%>
        <% if thongtincanhan.filedinhkem? %>
          <%= form.label :filename, thongtincanhan.filedinhkem_identifier %>
        <% end %>
      </div>
    </div>
  </fieldset>
  <div class="actions text-right">
    <%= form.submit 'Submit', class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/admin/thongtincanhans/edit.html.erb
<% if notice.present? %>
  <div class="alert alert-success alert-styled-left alert-arrow-left alert-bordered">
    <button type="button" class="close" data-dismiss="alert"><span>&times;</span><span class="sr-only">Close</span></button>
    <span class="text-semibold"><%= notice %></span>
  </div>
<% end %>
<div class="panel panel-flat">
  <div class="panel-heading">
    <h1 class="panel-title">Editing thông tin hồ sơ</h1>
  </div>
  <div class="panel-body">
    <%= render 'form', thongtincanhan: @thongtincanhan %>
    <%= link_to 'Back', admin_thongtincanhans_path %>
  </div>

</div>

app/views/admin/thongtincanhans/index.html.erb
<% if notice.present? %>
  <div class="alert alert-success alert-styled-left alert-arrow-left alert-bordered">
    <button type="button" class="close" data-dismiss="alert"><span>&times;</span><span class="sr-only">Close</span></button>
    <span class="text-semibold"><%= notice %></span>
  </div>
<% end %>

<div class="panel panel-flat">
  <div class="panel-heading">


    <div class="col-md-9">
      <h2 class="panel-title">Thông tin tuyển dụng</h2>
    </div>
    <div class="col-md-3">
      <%= link_to 'Tạo mới', new_admin_thongtincanhan_path , class: 'btn btn-primary btn-lg', id: 'new'%>
    </div>
  </div>
  <table class="table datatable-basic table-bordered">
    <thead>
    <tr>
      <th>Thông tin công việc</th>
      <th>Họ và tên</th>
      <th>Số điện thoại</th>
      <th>Email</th>
      <th>Vị trí công việc</th>
      <th>File đính kèm</th>
      <th class="text-center">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @thongtincanhans.each do |thongtincanhan| %>
      <tr>
        <td><%= thongtincanhan.thongtincongviec.tencongviec %></td>
        <td><%= thongtincanhan.hovaten %></td>
        <td><%= thongtincanhan.sodienthoai %></td>
        <td><%= thongtincanhan.email %></td>
        <td><%= thongtincanhan.vitricongviec.tenvitri %></td>
        <td><%= link_to thongtincanhan.filedinhkem_identifier, thongtincanhan.filedinhkem_url %></td>
        <td class="text-center">
          <ul class="icons-list">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="icon-menu9"></i>
              </a>

              <ul class="dropdown-menu dropdown-menu-right">
                <li><%= link_to 'Edit', edit_admin_thongtincanhan_path(thongtincanhan)  %></li>
                <li><%= link_to 'Destroy', [:admin, thongtincanhan], method: :delete, data: { confirm: 'Are you sure?' } %></li>
              </ul>
            </li>
          </ul>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/thongtincanhans/new.html.erb
<div class="panel panel-flat">
  <div class="panel-heading">
    <h1 class="panel-title">Tạo mới hồ sơ</h1>
  </div>
  <div class="panel-body">
    <%= render 'form', thongtincanhan: @thongtincanhan %>
    <%= link_to 'Back', admin_thongtincanhans_path %>
  </div>

</div>

app/views/admin/thongtincanhans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Thongtincongviec:</strong>
  <%= @thongtincanhan.thongtincongviec_id %>
</p>

<p>
  <strong>Hovaten:</strong>
  <%= @thongtincanhan.hovaten %>
</p>

<p>
  <strong>Sodienthoai:</strong>
  <%= @thongtincanhan.sodienthoai %>
</p>

<p>
  <strong>Email:</strong>
  <%= @thongtincanhan.email %>
</p>

<p>
  <strong>Vitricongviec:</strong>
  <%= @thongtincanhan.vitricongviec_id %>
</p>

<p>
  <strong>Filedinhkem:</strong>
  <%= @thongtincanhan.filedinhkem %>
</p>

<%= link_to 'Edit', edit_thongtincanhan_path(@thongtincanhan) %> |
<%= link_to 'Back', thongtincanhans_path %>